### ISSUE TITLE
docker-compose build gives error in windows 10 OS.

### ISSUE THREAD

**Issue by canbax** [graphistry/graph-app-kit#55] opened 2021-03-14 09:58 UTC
**Describe the bug**
I execute `docker-compose build`. Below are the console logs. It throws an error.

> D:\yusuf\graph-app-kit\src\docker>docker-compose build
> WARNING: The BASE_PATH variable is not set. Defaulting to a blank string.
> autoheal uses an image, skipping
> Building streamlit
> failed to get console mode for stdout: The handle is invalid.
> [+] Building 4.7s (8/15)
> [+] Building 4.8s (9/15)
>  => [internal] load build definition from Dockerfile                       0.1s 
>  => => transferring dockerfile: 32B                                        0.0s 
>  => [internal] load .dockerignore                                          0.0s 
>  => => transferring context: 2B                                            0.0s 
>  => [internal] load metadata for docker.io/graphistry/graphistry-forge-ba  2.0s 
>  => importing cache manifest from graphistry/graph-app-kit-st:latest       1.8s 
>  => [ 1/10] FROM docker.io/graphistry/graphistry-forge-base:v2.36.6-11.0@  0.0s 
>  => [internal] load build context                                          0.0s: exit code: 126
>  => => transferring context: 229B                                          0.0s 
>  => CACHED [ 2/10] WORKDIR /app                                            0.0s
>  => CACHED [ 3/10] COPY python/conda-app.sh ./                             0.0s
>  => ERROR [ 4/10] RUN source activate rapids && ./conda-app.sh             0.8s
> ------
>  > [ 4/10] RUN source activate rapids && ./conda-app.sh:
> #9 0.756 /bin/bash: ./conda-app.sh: /bin/bash^M: bad interpreter: No such file or directory
> ------
> ERROR: Service 'streamlit' failed to build
> 

**Expected behavior**
Work

**Observed behavior**
Error
**To Reproduce**
Clone the repo and then run `docker-compose build`

**Environment**
 - Windows 10 version 2004 (OS Build 19041.867)
 - StreamLit Version 0.77.0
- How you installed: git clone

**Additional context**

**Comment by lmeyerov** [comment] 2021-03-14 21:10
Thanks @canbax  

For tracking purposes, closing as a duplicate of https://github.com/graphistry/graph-app-kit/issues/39

For the particular trace above, the error suggests the docker context is not COPYING the `conda-app.sh` from the host context into the Docker container, so this sounds like a windows path issue. I recommend starting with that..

**Closed by lmeyerov** 2021-03-14 21:10 UTC
Labels: bug
